project:
  type: book
  output-dir: docs
  resources:
    - images
    - data/alum-first-job.csv

book:
  title: "Strategic Management Program Guide"
  favicon: images/strategy-centered-blue-grey-square.png
  date: "5/14/2025"
  chapters:
    - index.qmd
    - 01-courses.qmd
    - 02-tracks.qmd
    - 03-career.qmd
    - 04-clubs.qmd
    - 05-mentorship.qmd
    - 06-faculty.qmd
    - 07-apply.qmd
    - 08-faq.qmd
    
bibliography: references.bib

format:
  html:
    include-in-header: _header.html
    include-after-body: _footer.html
    theme: cosmo
    link-external-newwindow: true
    css: styles.css
    markdown: default
    
toc-title: On this page
      
number-sections: true

website:
  open-graph: true
  twitter-card:
    image: images/strat-logo.png
    card-style: summary_large_image



