project:
  type: book
  output-dir: docs
  resources:
    - images
    - data/alum-first-job.csv

book:
  title: "Strategic Management Program Guide"
  favicon: images/strategy-centered-blue-grey-square.png
  date: "5/14/2025"
  chapters:
    - index.qmd
    - 01-courses.qmd
    - 02-capstone.qmd
    - 03-career.qmd
    - 04-clubs.qmd
    - 05-mentorship.qmd
    - 06-faculty.qmd
    - 07-apply.qmd
    - 08-faq.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
    css: styles.css
    markdown: default
    includes:
      in-header: google-analytics.html
    
toc-title: On this page
      
number-sections: true



