project:
  type: book
  output-dir: docs
  resources:
    - images

book:
  title: "Strategic Management Program Guide"
  date: "5/14/2025"
  chapters:
    - index.qmd
    - 01-courses.qmd
    - 02-capstone.qmd
    - 03-career.qmd
    - 04-clubs.qmd
    - 05-faculty.qmd
    - 06-apply.qmd
    - 07-faq.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    markdown: default
    
toc-title: On this page
      
number-sections: true



