project:
  type: book
  output-dir: docs

book:
  title: "Strategic Management Program Guide"
  date: "5/14/2025"
  chapters:
    - index.qmd
    - 01-courses.qmd
    - 02-capstone.qmd
    - 03-career.qmd
    - 04-clubs.qmd
    - 05-faculty.qmd
    - 06-apply.qmd
    - 07-faq.qmd
    - 08-meet.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo



